version: '3.8'
services:
  uaic-app:
    image: python:3.11-slim
    container_name: uaic-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    command: bash -c "pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8001"
    restart: unless-stopped